/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package patients;

import appointments.Appointment;
import appointments.Frmappointments;
import Clinic.ClinicControl;
import Clinic.View;
import javax.swing.JOptionPane;

/**
 * @author matam
 */
public class FrmPatients extends javax.swing.JFrame implements View<Appointment> {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPatients.class.getName());
    private ClinicControl control;
    private Frmappointments vistaCitas;

    public FrmPatients() {
        initComponents();
        this.control = ClinicControl.getInstance(this);
    }

    // Constructor para enlazar la vista que contiene la JTable
    public FrmPatients(Frmappointments vistaCitas) {
        initComponents();
        this.vistaCitas = vistaCitas;
        this.control = ClinicControl.getInstance(this);
    }

    public void setVistaCitas(Frmappointments vistaCitas) {
        this.vistaCitas = vistaCitas;
    }

    @Override
    public void clear() {
        if (vistaCitas != null) {
            vistaCitas.limpiarSeleccion();
        }
    }

    @Override
    public void showData(Appointment data) {
        if (vistaCitas != null) {
            vistaCitas.showData(data);
        }
    }

    @Override
    public void showError(String error) {
        JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Información", JOptionPane.INFORMATION_MESSAGE);
    }

    public void actualizarTabla() {
        if (vistaCitas != null) {
            vistaCitas.actualizarTabla();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCargar = new javax.swing.JButton();
        btnReprogramar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAgendar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(this::btnCargarActionPerformed);

        btnReprogramar.setText("Reprogramar Cita");
        btnReprogramar.addActionListener(this::btnReprogramarActionPerformed);

        btnCancelar.setText("Cancelar Cita");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnAgendar.setText("Nueva Cita");
        btnAgendar.addActionListener(this::btnAgendarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnAgendar)
                .addGap(28, 28, 28)
                .addComponent(btnCargar)
                .addGap(18, 18, 18)
                .addComponent(btnReprogramar)
                .addGap(35, 35, 35)
                .addComponent(btnCancelar)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgendar)
                    .addComponent(btnCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReprogramar)
                    .addComponent(btnCancelar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        String code = javax.swing.JOptionPane.showInputDialog(this, "Código de la cita:");
        String id = javax.swing.JOptionPane.showInputDialog(this, "Cédula del Paciente:");
        String date = javax.swing.JOptionPane.showInputDialog(this, "Fecha (AAAA-MM-DD):");
        String time = javax.swing.JOptionPane.showInputDialog(this, "Hora (HH:MM):");
        String reason = javax.swing.JOptionPane.showInputDialog(this, "Motivo:");

        if (code != null && id != null && date != null && time != null) {
            try {
                patients.Patient p = control.findPatient(id);
                if (p == null) {
                    showError("El paciente no existe.");
                    return;
                }
                Appointment app = new Appointment(code, p, java.time.LocalDate.parse(date), java.time.LocalTime.parse(time), reason);
                if (control.scheduleAppointment(app)) {
                    showMessage("Cita registrada.");
                    actualizarTabla();
                } else {
                    showError("Código duplicado.");
                }
            } catch (Exception e) {
                showError("Formato de fecha u hora inválido.");
            }
        }
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnReprogramarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReprogramarActionPerformed
        if (vistaCitas == null) {
            showError("No hay tabla de citas conectada.");
            return;
        }
        String code = vistaCitas.getSeleccionado();
        if (code == null) {
            showError("Seleccione una cita de la tabla.");
            return;
        }
        String newDate = javax.swing.JOptionPane.showInputDialog(this, "Nueva fecha (AAAA-MM-DD):");
        String newTime = javax.swing.JOptionPane.showInputDialog(this, "Nueva hora (HH:MM):");

        if (newDate != null && newTime != null) {
            try {
                if (control.rescheduleAppointment(code, java.time.LocalDate.parse(newDate), java.time.LocalTime.parse(newTime))) {
                    showMessage("Cita reprogramada.");
                    actualizarTabla();
                } else {
                    showError("No se pudo reprogramar.");
                }
            } catch (Exception e) {
                showError("Formato inválido.");
            }
        }
    }//GEN-LAST:event_btnReprogramarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (vistaCitas == null) {
            showError("No hay tabla de citas conectada.");
            return;
        }
        String code = vistaCitas.getSeleccionado();
        if (code == null) {
            showError("Seleccione una cita de la tabla.");
            return;
        }
        if (control.cancelAppointment(code)) {
            showMessage("Cita cancelada.");
            actualizarTabla();
        } else {
            showError("No se pudo cancelar la cita.");
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new FrmPatients().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnReprogramar;
    // End of variables declaration//GEN-END:variables
}
